package com.doob.mathagent.agent.entity;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import java.time.Instant;

/**
 * MyBatis entity for agent_run_trace execution monitoring rows.
 */
@TableName("agent_run_trace")
public class AgentRunTraceEntity {

    /** Stable trace id generated by the execution service. */
    @TableId
    private String traceId;
    /** Source plan id used to link planning and execution. */
    private String planId;
    /** Trace creation time. */
    private Instant createdAt;
    /** Backend tenant id. */
    private String tenantId;
    /** Backend subject role. */
    private String subjectType;
    /** Backend subject id. */
    private String subjectId;
    /** Executed agent code. */
    private String agentCode;
    /** Selected provider name. */
    private String providerName;
    /** Selected model code. */
    private String modelCode;
    /** Execution status. */
    private String status;
    /** Estimated local cost. */
    private Double estimatedCost;
    /** JSON array of allowed tool scopes. */
    private String allowedToolScopesJson;
    /** JSON array of allowed data scopes. */
    private String allowedDataScopesJson;
    /** JSON array of evidence references. */
    private String evidenceRefsJson;
    /** Safe metadata JSON; raw prompts and raw model outputs are not stored. */
    private String metadataJson;

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public String getPlanId() {
        return planId;
    }

    public void setPlanId(String planId) {
        this.planId = planId;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public String getTenantId() {
        return tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public String getSubjectType() {
        return subjectType;
    }

    public void setSubjectType(String subjectType) {
        this.subjectType = subjectType;
    }

    public String getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    public String getAgentCode() {
        return agentCode;
    }

    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode;
    }

    public String getProviderName() {
        return providerName;
    }

    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    public String getModelCode() {
        return modelCode;
    }

    public void setModelCode(String modelCode) {
        this.modelCode = modelCode;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Double getEstimatedCost() {
        return estimatedCost;
    }

    public void setEstimatedCost(Double estimatedCost) {
        this.estimatedCost = estimatedCost;
    }

    public String getAllowedToolScopesJson() {
        return allowedToolScopesJson;
    }

    public void setAllowedToolScopesJson(String allowedToolScopesJson) {
        this.allowedToolScopesJson = allowedToolScopesJson;
    }

    public String getAllowedDataScopesJson() {
        return allowedDataScopesJson;
    }

    public void setAllowedDataScopesJson(String allowedDataScopesJson) {
        this.allowedDataScopesJson = allowedDataScopesJson;
    }

    public String getEvidenceRefsJson() {
        return evidenceRefsJson;
    }

    public void setEvidenceRefsJson(String evidenceRefsJson) {
        this.evidenceRefsJson = evidenceRefsJson;
    }

    public String getMetadataJson() {
        return metadataJson;
    }

    public void setMetadataJson(String metadataJson) {
        this.metadataJson = metadataJson;
    }
}
