package com.doob.mathagent.teacher.entity;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import java.time.LocalDateTime;

/**
 * MyBatis-Plus entity mapped to source_sync_checkpoint.
 */
@TableName("source_sync_checkpoint")
public class TeacherSourceSyncCheckpointEntity {

    /** Primary key generated by MySQL. */
    @TableId
    private Long id;
    /** Source synchronization job id. */
    private String jobId;
    /** Tenant that owns this checkpoint. */
    private String tenantId;
    /** Numeric source_document id. */
    private Long sourceDocumentId;
    /** Provider root token, such as a Feishu folder token. */
    private String rootToken;
    /** Folder token where traversal stopped. */
    private String currentFolderToken;
    /** Human-readable path where traversal stopped. */
    private String currentPath;
    /** Provider pagination token for the current folder page. */
    private String pageToken;
    /** JSON array of visited folder tokens. */
    private String visitedFolderTokensJson;
    /** JSON array of successfully downloaded items. */
    private String downloadedItemsJson;
    /** JSON array of failed items and retry metadata. */
    private String failedItemsJson;
    /** Checkpoint protocol version. */
    private Integer cursorVersion;
    /** Database creation timestamp. */
    private LocalDateTime createdAt;
    /** Database update timestamp. */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJobId() {
        return jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public String getTenantId() {
        return tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public Long getSourceDocumentId() {
        return sourceDocumentId;
    }

    public void setSourceDocumentId(Long sourceDocumentId) {
        this.sourceDocumentId = sourceDocumentId;
    }

    public String getRootToken() {
        return rootToken;
    }

    public void setRootToken(String rootToken) {
        this.rootToken = rootToken;
    }

    public String getCurrentFolderToken() {
        return currentFolderToken;
    }

    public void setCurrentFolderToken(String currentFolderToken) {
        this.currentFolderToken = currentFolderToken;
    }

    public String getCurrentPath() {
        return currentPath;
    }

    public void setCurrentPath(String currentPath) {
        this.currentPath = currentPath;
    }

    public String getPageToken() {
        return pageToken;
    }

    public void setPageToken(String pageToken) {
        this.pageToken = pageToken;
    }

    public String getVisitedFolderTokensJson() {
        return visitedFolderTokensJson;
    }

    public void setVisitedFolderTokensJson(String visitedFolderTokensJson) {
        this.visitedFolderTokensJson = visitedFolderTokensJson;
    }

    public String getDownloadedItemsJson() {
        return downloadedItemsJson;
    }

    public void setDownloadedItemsJson(String downloadedItemsJson) {
        this.downloadedItemsJson = downloadedItemsJson;
    }

    public String getFailedItemsJson() {
        return failedItemsJson;
    }

    public void setFailedItemsJson(String failedItemsJson) {
        this.failedItemsJson = failedItemsJson;
    }

    public Integer getCursorVersion() {
        return cursorVersion;
    }

    public void setCursorVersion(Integer cursorVersion) {
        this.cursorVersion = cursorVersion;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
