CREATE TABLE source_document (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    source_type VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    original_url TEXT NULL,
    local_path TEXT NULL,
    version VARCHAR(64) NULL,
    checksum VARCHAR(128) NULL,
    sync_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    parse_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    embedding_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    permission_scope VARCHAR(128) NOT NULL DEFAULT 'tenant',
    created_by VARCHAR(64) NULL,
    metadata_json JSON NULL,
    last_synced_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_source_document_tenant_type (tenant_id, source_type),
    KEY idx_source_document_status (sync_status, parse_status, embedding_status),
    KEY idx_source_document_checksum (checksum)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE document_block (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source_document_id BIGINT NOT NULL,
    external_block_id VARCHAR(128) NULL,
    block_type VARCHAR(32) NOT NULL,
    block_order INT NOT NULL DEFAULT 0,
    chapter VARCHAR(255) NULL,
    section VARCHAR(255) NULL,
    page_no INT NULL,
    printed_page_no VARCHAR(64) NULL,
    raw_text LONGTEXT NULL,
    normalized_text LONGTEXT NULL,
    image_refs JSON NULL,
    formula_refs JSON NULL,
    checksum VARCHAR(128) NULL,
    confidence DECIMAL(8,6) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_document_block_source_page (source_document_id, page_no, block_order),
    KEY idx_document_block_external (external_block_id),
    KEY idx_document_block_checksum (checksum),
    CONSTRAINT fk_document_block_source_document
        FOREIGN KEY (source_document_id) REFERENCES source_document(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE retrieval_query_log (
    query_id CHAR(36) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    subject_type VARCHAR(32) NULL,
    subject_id VARCHAR(64) NULL,
    query_text TEXT NOT NULL,
    retrieval_strategy VARCHAR(64) NOT NULL,
    requested_limit INT NOT NULL,
    hit_count INT NOT NULL DEFAULT 0,
    elapsed_ms INT NULL,
    request_context_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (query_id),
    KEY idx_retrieval_query_created_at (created_at),
    KEY idx_retrieval_query_tenant_strategy (tenant_id, retrieval_strategy, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE retrieval_hit_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    query_id CHAR(36) NOT NULL,
    rank_no INT NOT NULL,
    chunk_id VARCHAR(128) NOT NULL,
    doc_id VARCHAR(128) NOT NULL,
    book_name VARCHAR(255) NULL,
    page_no INT NULL,
    printed_page_no VARCHAR(64) NULL,
    score DECIMAL(12,6) NOT NULL,
    retrieval_strategy VARCHAR(64) NOT NULL,
    page_quality_label VARCHAR(64) NULL,
    source_page_image VARCHAR(512) NULL,
    evidence_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_retrieval_hit_query_rank (query_id, rank_no),
    KEY idx_retrieval_hit_doc_page (doc_id, page_no),
    KEY idx_retrieval_hit_quality (page_quality_label),
    CONSTRAINT fk_retrieval_hit_query
        FOREIGN KEY (query_id) REFERENCES retrieval_query_log(query_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE capability_audit_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_id CHAR(36) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    subject_type VARCHAR(32) NULL,
    subject_id VARCHAR(64) NULL,
    action VARCHAR(64) NOT NULL,
    path VARCHAR(255) NOT NULL,
    request_hash VARCHAR(128) NULL,
    idempotency_key VARCHAR(128) NULL,
    token_hash CHAR(64) NULL,
    decision VARCHAR(32) NOT NULL,
    reason TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_capability_audit_event (event_id),
    KEY idx_capability_audit_created_at (created_at),
    KEY idx_capability_audit_subject (tenant_id, subject_type, subject_id, occurred_at),
    KEY idx_capability_audit_action_decision (action, decision, occurred_at),
    KEY idx_capability_audit_token_hash (token_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE security_audit_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    subject_type VARCHAR(32) NULL,
    subject_id VARCHAR(64) NULL,
    endpoint VARCHAR(255) NOT NULL,
    action VARCHAR(64) NOT NULL,
    ip VARCHAR(64) NULL,
    device_id VARCHAR(128) NULL,
    user_agent VARCHAR(512) NULL,
    token_jti VARCHAR(128) NULL,
    api_key_id VARCHAR(128) NULL,
    model_name VARCHAR(128) NULL,
    estimated_cost DECIMAL(12,6) NULL,
    actual_cost DECIMAL(12,6) NULL,
    risk_score DECIMAL(8,6) NULL,
    result VARCHAR(32) NOT NULL,
    reason TEXT NULL,
    metadata_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_security_audit_created_at (created_at),
    KEY idx_security_audit_subject (subject_type, subject_id, created_at),
    KEY idx_security_audit_action_result (action, result, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
