-- A task may fail and be resumed repeatedly. The old unique (task_id,event_type) key silently discarded every
-- resume after the first one. Initial-create idempotency now lives in the deterministic event_id generated by Java,
-- while this non-unique index keeps task history queries efficient.
ALTER TABLE lecture_task_outbox_event
    DROP INDEX uk_lecture_task_outbox_task_event,
    ADD INDEX idx_lecture_task_outbox_task_event (task_id, event_type);
