-- Immutable provider accounting and end-to-end handout telemetry.
-- Java owns Flyway; the Python ai_runtime account receives only DML grants after this migration succeeds.
CREATE TABLE IF NOT EXISTS ai_usage_event (
    usage_event_id BIGINT NOT NULL AUTO_INCREMENT,
    run_id VARCHAR(80) NOT NULL,
    provider VARCHAR(80) NOT NULL,
    model_code VARCHAR(160) NOT NULL,
    attempt_no INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    prompt_tokens BIGINT NOT NULL,
    cached_prompt_tokens BIGINT NULL,
    completion_tokens BIGINT NOT NULL,
    total_tokens BIGINT NOT NULL,
    estimated_cost DECIMAL(20, 8) NULL,
    cost_known BOOLEAN NOT NULL DEFAULT FALSE,
    price_version VARCHAR(80) NULL,
    usage_source VARCHAR(40) NOT NULL,
    error_code VARCHAR(120) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (usage_event_id),
    UNIQUE KEY uq_ai_usage_attempt (run_id, provider, model_code, attempt_no),
    KEY idx_ai_usage_run_created (run_id, created_at),
    KEY idx_ai_usage_provider_model_status (provider, model_code, status)
);

CREATE TABLE IF NOT EXISTS handout_run_metrics (
    run_id VARCHAR(80) NOT NULL,
    task_id VARCHAR(100) NOT NULL,
    workflow_code VARCHAR(80) NOT NULL,
    result_status VARCHAR(32) NOT NULL,
    trace_id VARCHAR(120) NULL,
    submitted_at TIMESTAMP(6) NULL,
    enqueued_at TIMESTAMP(6) NULL,
    claimed_at TIMESTAMP(6) NULL,
    python_started_at TIMESTAMP(6) NULL,
    publication_gate_at TIMESTAMP(6) NULL,
    xelatex_started_at TIMESTAMP(6) NULL,
    completed_at TIMESTAMP(6) NULL,
    failed_at TIMESTAMP(6) NULL,
    acknowledged_at TIMESTAMP(6) NULL,
    queue_wait_ms BIGINT NULL,
    lease_wait_ms BIGINT NULL,
    ack_latency_ms BIGINT NULL,
    pdf_elapsed_ms BIGINT NULL,
    request_bytes BIGINT NULL,
    response_bytes BIGINT NULL,
    retry_count INT NULL,
    dlq_count INT NULL,
    cpu_samples_json JSON NULL,
    rss_samples_json JSON NULL,
    gpu_samples_json JSON NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (run_id),
    KEY idx_handout_run_metrics_workflow_status (workflow_code, result_status),
    KEY idx_handout_run_metrics_completed (completed_at)
);

CREATE TABLE IF NOT EXISTS handout_node_metrics (
    run_id VARCHAR(80) NOT NULL,
    node_code VARCHAR(80) NOT NULL,
    started_at TIMESTAMP(6) NULL,
    finished_at TIMESTAMP(6) NULL,
    elapsed_ms BIGINT NULL,
    provider VARCHAR(80) NULL,
    model_code VARCHAR(160) NULL,
    provider_calls INT NOT NULL DEFAULT 0,
    java_requests INT NOT NULL DEFAULT 0,
    payload_bytes BIGINT NOT NULL DEFAULT 0,
    prompt_tokens BIGINT NOT NULL DEFAULT 0,
    cached_prompt_tokens BIGINT NULL,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    total_tokens BIGINT NOT NULL DEFAULT 0,
    estimated_cost DECIMAL(20, 8) NULL,
    cost_known BOOLEAN NOT NULL DEFAULT FALSE,
    error_code VARCHAR(120) NULL,
    PRIMARY KEY (run_id, node_code),
    KEY idx_handout_node_metrics_provider_model (provider, model_code)
);
