package com.doob.mathagent.teacher.block.entity;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * MyBatis-Plus entity mapped to document_block.
 */
@TableName("document_block")
public class TeacherDocumentBlockEntity {

    /** Primary key generated by MySQL. */
    @TableId
    private Long id;
    /** Numeric source_document id. */
    private Long sourceDocumentId;
    /** Source-specific block id for idempotent tracing. */
    private String externalBlockId;
    /** Block type, such as markdown or text. */
    private String blockType;
    /** Order within the source document. */
    private Integer blockOrder;
    /** Chapter title inferred from source text. */
    private String chapter;
    /** Section title inferred from source text. */
    private String section;
    /** Page number when available. */
    private Integer pageNo;
    /** Printed page label when available. */
    private String printedPageNo;
    /** Stable relative source path used for incremental sync and rerank. */
    private String sourcePath;
    /** Coarse semantic role used by stage-two block rerank. */
    private String blockRole;
    /** Raw extracted text. */
    private String rawText;
    /** Normalized retrieval text. */
    private String normalizedText;
    /** JSON image reference array. */
    private String imageRefs;
    /** JSON formula reference array. */
    private String formulaRefs;
    /** JSON array of aligned knowledge graph node ids. */
    private String graphNodeIdsJson;
    /** JSON array of aligned graph tag names. */
    private String graphTagNamesJson;
    /** Content checksum. */
    private String checksum;
    /** Extraction confidence. */
    private Double confidence;
    /** Block lifecycle status. */
    private String status;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSourceDocumentId() {
        return sourceDocumentId;
    }

    public void setSourceDocumentId(Long sourceDocumentId) {
        this.sourceDocumentId = sourceDocumentId;
    }

    public String getExternalBlockId() {
        return externalBlockId;
    }

    public void setExternalBlockId(String externalBlockId) {
        this.externalBlockId = externalBlockId;
    }

    public String getBlockType() {
        return blockType;
    }

    public void setBlockType(String blockType) {
        this.blockType = blockType;
    }

    public Integer getBlockOrder() {
        return blockOrder;
    }

    public void setBlockOrder(Integer blockOrder) {
        this.blockOrder = blockOrder;
    }

    public String getChapter() {
        return chapter;
    }

    public void setChapter(String chapter) {
        this.chapter = chapter;
    }

    public String getSection() {
        return section;
    }

    public void setSection(String section) {
        this.section = section;
    }

    public Integer getPageNo() {
        return pageNo;
    }

    public void setPageNo(Integer pageNo) {
        this.pageNo = pageNo;
    }

    public String getPrintedPageNo() {
        return printedPageNo;
    }

    public void setPrintedPageNo(String printedPageNo) {
        this.printedPageNo = printedPageNo;
    }

    public String getSourcePath() {
        return sourcePath;
    }

    public void setSourcePath(String sourcePath) {
        this.sourcePath = sourcePath;
    }

    public String getBlockRole() {
        return blockRole;
    }

    public void setBlockRole(String blockRole) {
        this.blockRole = blockRole;
    }

    public String getRawText() {
        return rawText;
    }

    public void setRawText(String rawText) {
        this.rawText = rawText;
    }

    public String getNormalizedText() {
        return normalizedText;
    }

    public void setNormalizedText(String normalizedText) {
        this.normalizedText = normalizedText;
    }

    public String getImageRefs() {
        return imageRefs;
    }

    public void setImageRefs(String imageRefs) {
        this.imageRefs = imageRefs;
    }

    public String getFormulaRefs() {
        return formulaRefs;
    }

    public void setFormulaRefs(String formulaRefs) {
        this.formulaRefs = formulaRefs;
    }

    public String getGraphNodeIdsJson() {
        return graphNodeIdsJson;
    }

    public void setGraphNodeIdsJson(String graphNodeIdsJson) {
        this.graphNodeIdsJson = graphNodeIdsJson;
    }

    public String getGraphTagNamesJson() {
        return graphTagNamesJson;
    }

    public void setGraphTagNamesJson(String graphTagNamesJson) {
        this.graphTagNamesJson = graphTagNamesJson;
    }

    public String getChecksum() {
        return checksum;
    }

    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }

    public Double getConfidence() {
        return confidence;
    }

    public void setConfidence(Double confidence) {
        this.confidence = confidence;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}

