package com.doob.mathagent.securityrisk.entity;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import java.time.Instant;

/**
 * MyBatis-Plus entity mapped to capability_audit_log.
 */
@TableName("capability_audit_log")
public class CapabilityAuditLogEntity {

    /** Database primary key. */
    @TableId
    private Long id;

    /** Stable audit event id generated by the capability service. */
    private String eventId;

    /** Event timestamp from the capability service clock. */
    private Instant occurredAt;

    /** Backend resolved tenant id. */
    private String tenantId;

    /** Backend resolved subject type. */
    private String subjectType;

    /** Backend resolved subject id. */
    private String subjectId;

    /** Capability action code. */
    private String action;

    /** Capability-bound API path. */
    private String path;

    /** Capability-bound request body hash. */
    private String requestHash;

    /** Business idempotency key. */
    private String idempotencyKey;

    /** SHA-256 hash of the opaque token; raw token is never persisted. */
    private String tokenHash;

    /** Audit decision, such as issued, consumed, rejected, or denied. */
    private String decision;

    /** Human-readable decision reason. */
    private String reason;

    /**
     * Returns the primary key.
     *
     * @return primary key
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the primary key.
     *
     * @param id primary key
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the audit event id.
     *
     * @return audit event id
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Sets the audit event id.
     *
     * @param eventId audit event id
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * Returns the event timestamp.
     *
     * @return event timestamp
     */
    public Instant getOccurredAt() {
        return occurredAt;
    }

    /**
     * Sets the event timestamp.
     *
     * @param occurredAt event timestamp
     */
    public void setOccurredAt(Instant occurredAt) {
        this.occurredAt = occurredAt;
    }

    /**
     * Returns the tenant id.
     *
     * @return tenant id
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * Sets the tenant id.
     *
     * @param tenantId tenant id
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * Returns the subject type.
     *
     * @return subject type
     */
    public String getSubjectType() {
        return subjectType;
    }

    /**
     * Sets the subject type.
     *
     * @param subjectType subject type
     */
    public void setSubjectType(String subjectType) {
        this.subjectType = subjectType;
    }

    /**
     * Returns the subject id.
     *
     * @return subject id
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * Sets the subject id.
     *
     * @param subjectId subject id
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * Returns the action code.
     *
     * @return action code
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the action code.
     *
     * @param action action code
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * Returns the API path.
     *
     * @return API path
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the API path.
     *
     * @param path API path
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Returns the request hash.
     *
     * @return request hash
     */
    public String getRequestHash() {
        return requestHash;
    }

    /**
     * Sets the request hash.
     *
     * @param requestHash request hash
     */
    public void setRequestHash(String requestHash) {
        this.requestHash = requestHash;
    }

    /**
     * Returns the idempotency key.
     *
     * @return idempotency key
     */
    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    /**
     * Sets the idempotency key.
     *
     * @param idempotencyKey idempotency key
     */
    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    /**
     * Returns the token hash.
     *
     * @return token hash
     */
    public String getTokenHash() {
        return tokenHash;
    }

    /**
     * Sets the token hash.
     *
     * @param tokenHash token hash
     */
    public void setTokenHash(String tokenHash) {
        this.tokenHash = tokenHash;
    }

    /**
     * Returns the audit decision.
     *
     * @return audit decision
     */
    public String getDecision() {
        return decision;
    }

    /**
     * Sets the audit decision.
     *
     * @param decision audit decision
     */
    public void setDecision(String decision) {
        this.decision = decision;
    }

    /**
     * Returns the decision reason.
     *
     * @return decision reason
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the decision reason.
     *
     * @param reason decision reason
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}
